# NOTE: This is just for testing deployments
services:
  app:
    image: nginx:latest
    environment:
      test: true
    ports:
      - "81:80"
    volumes:
      - test:/var/www/html

volumes:
  test: